### ISSUE TITLE
Handle transcription comments being posted in reply to the tor bot

### ISSUE THREAD

**Issue by PejmanPoh** [GrafeasGroup/tor#105]
Suggestion by @TheLonelyGhost.

Have the bot reply with something to the effect of "Hey! Stop that! Post it to the original post up there! ^^" whenever a user posts a transcription comment as a reply to the bot rather than the original post.

**Comment by itsthejoker** [comment]
We can just look for the validation key in a new comment -- this seems like an easy change. Let's hold off until the new distributed release.
