### ISSUE TITLE
No check that the person who typed "done" claimed it

### ISSUE THREAD

**Issue by codingJWilliams** [GrafeasGroup/tor#108]
For a post like https://www.reddit.com/r/TranscribersOfReddit/comments/85kmc5/oldpeoplefacebook_image_please_help/ where /u/deadespeon claimed, /u/athousandwordsworth claimed, didn't wait for a response, transcribed, and typed `done`, the bot marked the post as complete even though kau's claim was not accepted

**Comment by codingJWilliams** [comment]
(See #transcribing, at 4:20 GMT 19/03/18)

**Comment by itsthejoker** [comment]
https://github.com/GrafeasGroup/tor/pull/88
