### ISSUE TITLE
Identify method for users to block our content on desktop

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#11]
We've heard from several people that they do not wish to view our posts, especially on desktop. Investigate and implement process for blocking our posts on desktop, probably by using the header.

**Comment by TheLonelyGhost** [comment]
How do you mean block the posts?

Are the users browsing /r/faceplam, they see a comment posted by the bot with the transcription and they don't want to see that comment?

Or are you talking about browsing /r/frontpage and seeing /r/TranscribersOfReddit posts?

**Comment by itsthejoker** [comment]
The first one. It's been reported several times from r/facepalm users, but it would be a nice thing to find in general.

We currently have a hack that involves using RES and adding a custom filter to the .js file that allows you to remove a comment based on text, and then you use our header as the filter text. However, this is really slow and kind of painful for most machines, so there needs to be some investigation to see if there's a better way to do this.

**Comment by captcoe** [comment]
Another note: we've received a message from a user saying that the custom .js file is incompatible with the current version of RES, so that might not even be a temporary solution.

**Comment by itsthejoker** [comment]
Oh, that's irritating.

**Comment by TheLonelyGhost** [comment]
I haven't hacked on any custom .js for RES yet. Is there some place where I could view it? Might be able to throw something together this week, depending on how easy it is to ramp up on it.

**Comment by captcoe** [comment]
Yep, the code is right here: https://gist.github.com/patch-werk/8722819

**Comment by perryprog** [comment]
I got something awesome!

@Kumalumajuma is a genius, and came up with the idea of using uBlock Origin's custom filters.

Add this line to the tab under "My Filters"
`www.reddit.com##.sitetable.nestedlisting > div:has-text(I'm a human volunteer content transcriber for Reddit!)`

**Comment by perryprog** [comment]
[Here is the opposite (which you saw in slack already)](https://gist.githubusercontent.com/perryprog/767eace4307bb205553c6f36b0a40884/raw/35065ce16c43318cf68d84230ebcd7a383b91d7b/tor_autoscroll.user.js)

AFAIK, it'll only work with Tampermonkey. If you have it installed, that should open up a window asking to install it and stuff.

**Comment by perryprog** [comment]
OK! [This](https://gist.github.com/perryprog/767eace4307bb205553c6f36b0a40884) is a compilation of everything that could be helpful. Sorry for the comment spam, btw.

To get the tamper monkey install link, find the file you want the link for in that gist, then right click on "Raw" (top right of each file), and copy the link.

Tamper-monkey will automagically install the plugin-thingy with this. 🎉

**Comment by TheLonelyGhost** [comment]
Just need confirmation the uBlock Origin script works and we can add instructions to the /r/ToR wiki. That should close this ticket out.

As an aside, I was inspired by @perryprog's user script and created one of my own. This one takes advantage of certain ARIA hooks used by Chromevox for screen reading. Tested and it actually pulls the screen reader's attention to start in the transcription comment body. Doesn't work so well if the transcription comment is hidden behind a "load more comments" link... 😢

**Comment by perryprog** [comment]
Ah, shoot I didn't think about the Load More Comments bit. Shoot...

And the uBlock Origin script does work fine, but if you do want to see the transcription, you'll have to pause tracking first.

**Comment by perryprog** [comment]
Also, seems like your script should be adaptable for removing/collapsing transcriptions as a tamper monkey script, if we want to do that. (since it might not always block them because Reddit's Load More Comments)

**Comment by TheLonelyGhost** [comment]
It makes sense that the logic can largely be reused for hiding the comments, but I think uBlock Origin is a more sustainable and more efficient route to that end. Kudos for finding that! 🎉

**Comment by perryprog** [comment]
No problem! However, there's no reason _not_ to list all of the options.

If someone doesn't have uBlock Origin, but they have tamper-monkey, they would rather use that (probably). Also, I added some scripts for Tamper-monkey in the gist I linked earlier, however they don't use the best JavaScript logic ever.
