### ISSUE TITLE
Add support for Ruby rank (2500+)

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#111]
Needs to be added both in the bot and in the subreddit.

**Comment by TheLonelyGhost** [comment]
@itsthejoker What css class should be applied for ruby rank?

**Comment by itsthejoker** [comment]
I need to make one. Un momento.

**Comment by itsthejoker** [comment]
Use `grafeas-ruby`.

**Comment by TheLonelyGhost** [comment]
Huh, this should have been closed already. [Fixed](https://github.com/GrafeasGroup/tor/blob/f4a82102e85f47b85dda08723c70fb6e7708dd8a/tor/helpers/flair.py#L39-L40)
