### ISSUE TITLE
New post flair: Accepting CoC

### ISSUE THREAD

**Issue by perryprog** [GrafeasGroup/tor#112]
There have been several instances of new transcribers that are accepting the CoC, but by the time they are done someone has already claimed the post.

There are two solutions here, mark the post as Claimed when a user is accepting the CoC, or add a new flair called Accepting CoC, which would also allow us to have a custom message response when someone tries to claim it when someone's accepting it.

(This should be held til v4)

**Comment by DavidArchibald** [comment]
I think the better solution here is the custom flair, because a new user can theoretically not accept the CoC, plus it could potentially help moderation.

**Comment by perryprog** [comment]
Agreed, it also makes more sense.

**Comment by TheLonelyGhost** [comment]
Closing as stale. Would be better implemented with Blossom already tracking a post's status and implementing it with another set of actions by `tor` in the event loop.
