### ISSUE TITLE
Handle for same user commenting "claim" twice

### ISSUE THREAD

**Issue by codingJWilliams** [GrafeasGroup/tor#115]
Theres an edge case where a user accidentally double claims, just putting it here to consider, should be a simple edge case to add in

https://i.imgur.com/ej9tjPL.png

**Comment by arfie** [comment]
What are you suggesting here? I believe you're referencing to the common problem on reddit where posts and comments get submitted multiple times on a slow network, if the user clicks "submit" multiple times.

I can see the second message "This post has already been claimed" could be confusing if this were to happen to a user. Perhaps we could change it to "You have already claimed this post!" if it's the same user who "originally" claimed it?

**Comment by codingJWilliams** [comment]
Aye, that’s what I’m suggesting :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheLonelyGhost** [comment]
Moving discussion to more recent issue based on current architecture (instead of years-old one): #187
