### ISSUE TITLE
Add flair "OP transcribed"

### ISSUE THREAD

**Issue by astheriae** [GrafeasGroup/tor#119]
Add a flair option "OP transcribed" for when we are trying to recruit an OP that has transcribed the post when making it. 

Would act like an 'unclaimed' post, being removed if the OP didn't come to join us.

If they did, it would process as normal, CoC and sent to archive. (Then we get a new transcriber, yay)

Could maybe even have a bot message when someone claims it along the lines of

"Are you the OP of this post? If yes, thanks for getting involved and transcribing the post! If not, this post has already been transcribed, feel free to pick another post in our queue!"

**Comment by codingJWilliams** [comment]
I feel like this brings up a couple of issues / questions in my mind
 - How do we know when the OP transcribed? We could compare each comment to OCR but that's temperamental
 - `Would act like an 'unclaimed' post` > So even though the OP has transcribed it, I could claim it and transcribe it?
 - How often do we see OPs transcribing themselves? I can remember about 5 transcriptions where the op did that, max
 - `"Are you the OP of this post? If yes, thanks for getting involved and transcribing the post! If not, this post has already been transcribed, feel free to pick another post in our queue!"` - we can detect pretty easily whether someone is the OP of the post or not ^.^

Don't mind me, just thrashing the idea round a bit :laughing: We can look into this defo

**Comment by TimJentzsch** [comment]
> How do we know when the OP transcribed? We could compare each comment to OCR but that's temperamental

Instead of detecting it automatically, it would be possible to add another bot command similar to `claim` to mark a post as OP transcribed manually. I.e. if you check out a post and the OP has transcribed it already, you can mark it as `OP transcribed` to remove it from the queue.

However, the OP would not know about this so they would probably not join.

**Comment by MurdoMaclachlan** [comment]
It would be theoretically quite easy to have the bot detect the command and send a message to the OP letting them know, but I wonder what the situation would be if they don't want to join for whatever reason, but would like to keep transcribing their own posts themselves. It could get pretty annoying to have messages from the bot again and again in that scenario.

A way for a user to voluntarily "blacklist" themself from such messages might be possible, but again, people might not want to go through the hassle. Alternatively, perhaps the bot could have a list of people it has already messaged for transcribing their own post and doesn't message them again?

Just throwing some possibilities around.

**Comment by TheLonelyGhost** [comment]
This seems like something that should be part of the "report post" flow, assuming it isn't a frequent occurrence. Mods removing from queue because OP already did the work on their own seems reasonable.

**Comment by TheLonelyGhost** [comment]
Just confirmed, the current workflow transcribers are expected to follow is to report the post with the reason "OP has transcribed post". No bot automation necessary since mods would remove it from the queue.
