### ISSUE TITLE
Change post workers so that they're using the pushshift API instead of scraping the reddit json

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#133]
Example: https://api.pushshift.io/reddit/search/submission?subreddit=oldpeoplefacebook&sort_type=created_utc&after=1d&sort=desc

**Comment by TheLonelyGhost** [comment]
Not to shoot it down, but why use Pushshift.io instead of Reddit? What's the benefit? What are the drawbacks?

**Comment by itsthejoker** [comment]
As much as I would like to make this change, I am closing it as infeasible because pushshift does not updates scores in a timely manner. All posts show a score of one, which would make the filters completely unreliable and would still require calls to reddit in order to verify, which would completely defeat the purpose.
