### ISSUE TITLE
Failed URL escaping

### ISSUE THREAD

**Issue by TheLonelyGhost** [GrafeasGroup/tor#163]
Example case: https://www.reddit.com/r/TranscribersOfReddit/comments/c1sugf/boneappletea_image_dampa_test/

Note the `D&amp;A test` compared to the original post's `D&A test`.

**Comment by TheLonelyGhost** [comment]
More than likely this is related to the version of PRAW we're currently on. I'd like to see that updated first to see if this goes away.

**Comment by NGTmeaty** [comment]
Another example: https://www.reddit.com/r/TranscribersOfReddit/comments/cvfxf1/programmerhumor_image_for_gt_while_change_my_mind/

**Comment by Pf441** [comment]
Poke for this issue, since PRAW has been updated recently.

**Comment by TheLonelyGhost** [comment]
I'm going to assume that this has been fixed with the (not-so-)new update to praw. If it's observed again, please reopen this and we'll dig in and try to find a root cause here.
