### ISSUE TITLE
Automated testing for ToR bot

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#2]
Add tests able to be run with pytest.

- [ ] Stub out all calls to Reddit
- [ ] Test interfaces with dependencies (e.g., tor_core, praw, redis) to make updates easier
- [x] Remove exception reporting to Bugsnag/Sentry/whoever when running tests

**Comment by TheLonelyGhost** [comment]
Currently has tests using unittest and there is another ticket open (#32) for Travis CI support. They need to be improved, but there is _some_ test support now...

Closing due to being split up into smaller tasks.

**Comment by TheLonelyGhost** [comment]
I'm stupid. This is testing for the main admin bot, not the project as a whole.

**Comment by TheLonelyGhost** [comment]
Here's a great library by the same people who make Sentry: https://github.com/getsentry/responses

Since PRAW uses the requests library under the covers (like a sane person would), this makes it stupid-simple to stub out calls to unknown locations and test the application, including upgrades to PRAW, as a whole.

**Comment by perryprog** [comment]
Wow, that looks incredibly awesome. I _might_ at some point be able to check that out, and see how we could use it.

**Comment by TheLonelyGhost** [comment]
I'd also like to address one of the items in the original description:

> - [ ] Remove exception reporting to Bugsnag/Sentry/whoever when running tests

This is something that should never be an issue. We should just not have a local file, frankly ever, and use environment variables only. Then we should only set those environment variables when we are actually running in production. Full stop.

The goal of this is to never test in production anyway, and those keys are for production use only.

**Comment by TheLonelyGhost** [comment]
There's already some automated testing for the ToR bot and there are some pre-cursor actions that need to take place for this to have any effect.

Given #156 is set to replace PRAW, that will simplify the testing story significantly. #157 will also lower the surface area of the tests without needing to do as much refactoring, at least so we can see what assumptions can be made about the returned datatypes.

I suggest we hold off on this until #156 and #157 are complete. Test support would also be better suited as incrementally increasing, not a one-off bug to "fix". Closing in favor of more targeted objectives for testing.
