### ISSUE TITLE
Subreddit filter not working 100%

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#226]
Issue that r/historyporn pulls in posts that are below the upvote threshold (theorized it's b/c they manually approve every post). The current upvote filter on r/historyporn is 70

Examples:
(50 points) https://www.reddit.com/r/TranscribersOfReddit/comments/o4aa4b/historyporn_image_a_young_widow_grieves_over_the/
(18 points) https://www.reddit.com/r/TranscribersOfReddit/comments/o4aa31/historyporn_image_gandhi_middle_row_fifth_from/
(23 points) https://www.reddit.com/r/TranscribersOfReddit/comments/o4aj8q/historyporn_image_mother_and_child_in_gas_masks/
(31 points) https://www.reddit.com/r/TranscribersOfReddit/comments/o4aime/historyporn_image_1915_ww1_french_trench_raider/

**Comment by TimJentzsch** [comment]
I think the problem here was that the sub wasn't correctly capitalized, it has been resolved now.
