### ISSUE TITLE
Reply with special message when a new rank has been reached

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/tor#256]
When a user reaches a new rank, only their flair changes, some users might miss that.

The bot should answer with an altered `done` message when a new rank has been reached, gratulating and thanking the user for his help.

**Comment by Arnab1181412** [comment]
Hey I want to fix this issue im new to github contributor and have good knowledge of python and can you give some context to it.

**Comment by TimJentzsch** [comment]
Sure. Are you already familiar with the transcribing process in general?

**Comment by Arnab1181412** [comment]
No sir but I can read the docs for that

**Comment by Arnab1181412** [comment]
Yes sir I have read the docs and know the transcribing process like how they do on reddit

**Comment by TimJentzsch** [comment]
Awesome! So after a volunteer finishes a transcription, they get one score ("gamma") for it. At certain thresholds, they earn a new rank. For example 1 transcription is "Inititate", 50 is "Green", 100 is "Teal", etc.

So when a volunteer completes a transcription with replying `done` to the bot, a rank upgrade should be reflected in the response.

The relevant code to process the `done` is here: https://github.com/GrafeasGroup/tor/blob/main/tor/core/user_interaction.py#L151-L271. The ranks (or flairs) are determined here: https://github.com/GrafeasGroup/tor/blob/fd28d150b4648cac98435dfdd685c7ea67f55f51/tor/helpers/flair.py#L41-L59.

To be honest, after looking closer at the code this might be harder to implement than I thought. Please let me know if you have any questions or problems and I'll be happy to help you out.

**Comment by Arnab1181412** [comment]
Sir I got the code so the lets say a user did 100 transcriptions so the bot will return the user **Teal**  updating his flair/rank so I should add a new special message besides just updating rank to Teal which will be sent to him as he reaches a new rank.

**Comment by itsthejoker** [comment]
Exactly!

**Comment by TimJentzsch** [comment]
Yes, so once the rank changes we wan't a new message. For that you can use the `message` variable in the function here: https://github.com/GrafeasGroup/tor/blob/main/tor/core/user_interaction.py#L151-L271

The strings for the messages are taken from this localization file: https://github.com/GrafeasGroup/tor/blob/main/tor/strings/en_US.yml
Which you can access via the `i18n` variable. In the function I linked above are a couple of examples for that.
So ideally we would have a new string there under `responses.done` which congratulates the user on reaching a new rank.

Don't worry too much about the message, we can always adjust it later!

**Comment by Arnab1181412** [comment]
Yes Sir I got that and have started working on that

**Comment by Arnab1181412** [comment]
Sir I had this one doubt I have to add message to https://github.com/GrafeasGroup/tor/blob/main/tor/strings/en_US.yml for responses.done

**Comment by Arnab1181412** [comment]
Sir I had this approach : 

After successful execution of  https://github.com/GrafeasGroup/tor/blob/fd28d150b4648cac98435dfdd685c7ea67f55f51/tor/core/user_interaction.py#L258 I can define a function in https://github.com/GrafeasGroup/tor/blob/fd28d150b4648cac98435dfdd685c7ea67f55f51/tor/helpers/flair.py which checks if the user has hit a particular milestone let's say it takes an argument 

> transcription_count

**Comment by Arnab1181412** [comment]
Sir I had this approach :

After successful execution of
https://github.com/GrafeasGroup/tor/blob/fd28d150b4648cac98435dfdd685c7ea67f55f51/tor/core/user_interaction.py#L258

I can define a function **check_promotion** in https://github.com/GrafeasGroup/tor/blob/fd28d150b4648cac98435dfdd685c7ea67f55f51/tor/helpers/flair.py which checks if the user has hit a particular milestone let's say it takes an argument **transcription_count** and lets say after the user is currently at 99 transcription after this transcription he reaches 100 then 100 is given as an argument to this **check_promotion** function then it will return **Teal** so this is passed to **responses.done.promoted.Teal**  (which has to be created in https://github.com/GrafeasGroup/tor/blob/fd28d150b4648cac98435dfdd685c7ea67f55f51/tor/strings/en_US.yml ) and this message retrieved from **responses.done.promoted.Teal** is stored in an alternate_promotion_message variable which is returned by https://github.com/GrafeasGroup/tor/blob/fd28d150b4648cac98435dfdd685c7ea67f55f51/tor/core/user_interaction.py#L152 function. Now if lets say that the user doesnt hit a particular rank and is in between rank so the alternate_promotion_message will return no value.


Sir what do you think of this approach and I had this one doubt that how do I retrieve **transcription_count**

**Comment by Arnab1181412** [comment]
When **alternate_promotion_message** returns no value it means the return value of **ckeck_promotion** is a None value.

**Comment by Arnab1181412** [comment]
And one more thing sir that after I am done with the code how do i perform test or a sanity check

**Comment by TimJentzsch** [comment]
Hey there, sorry for the delay.

The approach sounds good! You can get the `transcription_count` from the `blossom_user` object here: https://github.com/GrafeasGroup/tor/blob/fd28d150b4648cac98435dfdd685c7ea67f55f51/tor/core/user_interaction.py#L182

"Blossom" is our API where we store all the volunteer data. `blossom_user["gamma"]` should give you the transcription count the user had **before** this transcription was processed.

Testing this locally is very hard unfortunately, because we need to interact with both the Reddit API and our Blossom API. So instead we will just make a code review and then test in production 🙃 

Feel free to open a draft PR already if you want! And if you have any questions feel free to ask :)

**Comment by Arnab1181412** [comment]
Thank you sir I will get to work.

**Comment by Arnab1181412** [comment]
Sir if the user is completely new and and did 1 transcription so what is the rank allotted to him ?

**Comment by Arnab1181412** [comment]
https://github.com/GrafeasGroup/tor/pull/258#issue-704979985

**Comment by TimJentzsch** [comment]
With one transcription they get the "Initiate" role :)

**Comment by TimJentzsch** [comment]
Thanks for the contribution! I will take a look at it tomorrow

**Comment by Arnab1181412** [comment]
Ok sir

**Comment by Arnab1181412** [comment]
https://github.com/GrafeasGroup/tor/pull/259 

Sir this is the latest PR with initiate role added please review this one sir.

**Comment by Arnab1181412** [comment]
https://github.com/GrafeasGroup/tor/pull/260

Sir this is the latest PR with initiate role added please review this one sir..

**Comment by TimJentzsch** [comment]
Just as a note, you don't need to open a new PR every time you make changes, the old one will update automatically when you push a new commit :)

**Comment by Arnab1181412** [comment]
Sorry Sir I didnt know that and is there any issue with the code?

**Comment by TimJentzsch** [comment]
I didn't have time to review yet unfortunately, I hope I can do that soon

**Comment by Arnab1181412** [comment]
Sure Sir. Thank you

**Comment by TimJentzsch** [comment]
Sorry for the delay, I left you some comments now. Thanks for your help!

**Comment by TheodoreHua** [comment]
From what I can see, this issue has been resolved in #282 , someone with permissions should close the issue.
