### ISSUE TITLE
Fix Slack errors affecting `done`

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/tor#276]
When Slack is unresponsive, the transcription checks don't work. This seems to prevent the `done`s being saved to the database, but they are still flaired as completed on Reddit.

This in turn prevents users from claiming a new post.

**Comment by itsthejoker** [comment]
Fixed in https://github.com/GrafeasGroup/blossom/commit/5acdb433887b2ae115d13650a4db4d7417f383de
