### ISSUE TITLE
Fix wiki page links

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/tor#289]
The bot uses some of the old wiki pages, they should be updated.

- `format/audio` -> `formats/audio`
- `format/other` should be replaced by `format/images`

https://github.com/GrafeasGroup/tor/blob/main/tor/core/initialize.py#L49-L52

**Comment by MurdoMaclachlan** [comment]
`format/images` is already in there; `format/other` just needs to be removed ;)
