### ISSUE TITLE
Detect auto-removed transcriptions

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#30]
## Scenario

> $User claims a post on /r/TranscribersOfReddit.
> $User finds the linked content and transcribes it.
> $User posts transcription as top level comment to the subreddit where content was originally linked.
> Auto-moderator (or other bot) removes $User's transcription comment.

## Problem

/u/TranscribersOfReddit will thinks $User did not transcribe because it does not show up on the top-level comments of the post when checked.

## Workaround

/r/TranscribersOfReddit must manually verify in $User's post history that they did indeed post a transcription and override the bot's decision that it is not done.

## Proposed Fix

Change `done` verification method of the bot from looking at top level comments on the post to combing through $User's submissions

**Comment by TheLonelyGhost** [comment]
I edited the description above to clarify. Previously:

> Currently, if a transcription is automatically removed, then the bot comments that it cannot find the transcription and then we have to approve it manually.
> 
> Investigate loading the user's post history (last 5 comments, for example) and seeing if there is a valid transcription on a post that matches the title and completing the post as normal.

**Comment by perryprog** [comment]
We can close this 😄

**Comment by itsthejoker** [comment]
Resolved in https://github.com/GrafeasGroup/tor/pull/69
