### ISSUE TITLE
Disable formatting checks in code

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/tor#324]
Most formatting checks are not applicable within inline code or a codeblock. The detection should be disabled there.

Notably this only rarely causes issues so we can probably postpone the fix for now.

**Comment by itsthejoker** [comment]
https://www.reddit.com/r/TranscribersOfReddit/comments/wfx3se/programmerhumor_image_rust_feels_like_passive/iiwxhnu/  example place this causes issues
