### ISSUE TITLE
Fix bot not replying to the volunteer if the command wasn't recognized

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/tor#331]
In the past, the bot would let the volunteer know if a command could not be recognized by replying to them. This doesn't seem to be the case anymore, the reply is only forwarded to Slack.

This message should get re-introduced, ideally saying that the mods have been notified so that volunteers don't keep replying to the bot.

**Comment by MurdoMaclachlan** [comment]
Duplicate of #284? :P
