### ISSUE TITLE
Unescaped heading warning does not have backslash in escaped example.

### ISSUE THREAD

**Issue by MurdoMaclachlan** [GrafeasGroup/tor#350]
In the unescaped heading warning, the section that explains how to escape the heading doesn't have a backlash in its example:

![image](https://user-images.githubusercontent.com/47920497/184529440-26fd03dd-93b5-4cbf-9345-3d2e3910d893.png)

![image](https://user-images.githubusercontent.com/47920497/184529446-5c8e4bd3-6e74-434c-a691-41c67eb1eda4.png)

The relevant line of code is here:

https://github.com/GrafeasGroup/tor/blob/139a39b76f99b9a6fad4513aef6459ffbbddb8c4/tor/strings/en_US.yml#L334

From my (admittedly minimal) understanding of YAML, I think just adding an escaped backslash like `\\#Text` should be enough.

**Comment by TimJentzsch** [comment]
> From my (admittedly minimal) understanding of YAML, I think just adding an escaped backslash like \\#Text should be enough.

I think the escaping is not necessary in YAML, so \`\#Text\` should work.

**Comment by MurdoMaclachlan** [comment]
Looking at all the other YAML strings with backlashes that should be printed (e.g. 'unescaped_username' and 'unescaped_subreddit'), they all have the escaped backslash like `\\#`.

https://yamlchecker.com/ also flags it as an 'unknown escape sequence' if it's just `\#`, so I think we need the second one.

**Comment by TimJentzsch** [comment]
> Looking at all the other YAML strings with backlashes that should be printed (e.g. 'unescaped_username' and 'unescaped_subreddit'), they all have the escaped backslash like `\\#`.
> 
> https://yamlchecker.com/ also flags it as an 'unknown escape sequence' if it's just `\#`, so I think we need the second one.

It depends how you define the string. If you quote it, `\` is treated as an escape character so you need two of them.
If you do it with the `|` character then it's not necessary.

But in this case I think you're right, I misremembered how we defined the strings for the formatting messages
