### ISSUE TITLE
Admin commands framework

### ISSUE THREAD

**Issue by TheLonelyGhost** [GrafeasGroup/tor#70]
In order to empower our mods to do more without requiring the bot's source code to change, we should spend some time refining our admin commands framework.

We have commands like `ping` as an alive check, `!override`, and so on, but with #16 we are adding another admin command by way of `!blacklist`. In order to keep this type of evolution sustainable and consistently require a certain level of authority to invoke the directives, we should put them behind a framework so we can separate the authority check from the admin command itself. Less to think about that way.

Here's what I have in mind regarding the architecture:

- Receive message starting with `!` -> means parse the message like it's an admin command
- Check that message author is a moderator for the /r/tor subreddit
  - If not, maybe we want an early warning system here where it posts to slack noting `<user> attempted admin command <command>`?
- Parse content of subject after the initial `!` for how to route the command
  - Example: subject `!blacklist` -> python method for blacklisting a list of users
- Parse the content of message body for arguments the command takes
  - It might not directly be a python argument, but all input after authentication (is mod?) should come from the message body
- Log to file/stdout that `<user> called <action> via private message`
- Execute prescribed action
- Reply to message with output of action

**EDIT:** To clarify, this is intended to be once-in-a-while administrator override functionality. Events where something weird happened and the bot wasn't able to handle a situation, it might make sense for a mod to PM the bot to, for example, bump up the flair of a particular user. Or they might unclaim a post. Or other use cases. The idea is the bot should handle the large majority of cases, so this shouldn't need to scale out too much.

**Comment by perryprog** [comment]
Other idea: add a file syntax for this, something like (csv I guess)
```csv
commandname,needsmod,functionname
blacklist,true,blacklist_people
```

the function would then be called with the body as an argument, or maybe just the object for the message. The function could also return a reply to the person, with a new line for each separate operation.

Example:

```python
def blacklist_people(args, config):
    # Caller already checked for mod blah
    people = args.split('\n')
    suc = ""
    for person in people: 
        config.redis.SADD(person)
        # Check if person is blacklistable (if you guys want that I suppose)
        suc.append('Added {} to blacklist!\n', person.namethingy)
    return suc
    # checks for blacklist in inbox handling
```

This would result in         
```
┌───────────────────────────────────────┐                                                                    
│                                       │                                                                    
│                                       │                                                                    
│               Joker PMs               │                                                                    
│                                       │                                                                    
│          subject: !blacklist          │                                                                    
│        body: jabbathehutt1234         │────────────┐                                                       
│                captcoe                │            │                                                       
│              Gallowboob               │            │                                                       
│                                       │            │                                                       
│                                       │            │                                                       
│                                       │            │                                                       
└───────────────────────────────────────┘            │                                                       
                                                     │                                                       
                                                     │                                                       
                                                     │                                                       
                                                     │                                                       
                                                     │                                                       
                                                     │                                                       
                                                     │                                                       
                                                     │             ┌────────────────────────────────────────┐
                                                     │             │                                        │
                                                     └────────────▶│                                        │
                                                                   │              Bot parses:               │
                                                                   │                                        │
                                                                   │  - Checks csv for !blacklist command   │
                                                                   │        - checks if it needs mod        │
                                                                   │         - if so, checks for mod        │
                                                                   │    - if no mod, PM them with no_gifs   │
                                                                   │  - calls function with body args and   │
                                                                   │                 config                 │
                                                                   │     - PMs back result of function      │
                                                                   │                                        │
                                                       ┌───────────┤                                        │
                                                       │           │                                        │
                                                       │           └────────────────────────────────────────┘
                                                       │                                                     
                                                       │                                                     
                                                       │                                                     
┌────────────────────────────────────────┐             │                                                     
│                                        │             │                                                     
│                                        │             │                                                     
│                                        │             │                                                     
│                                        │             │                                                     
│                                        │             │                                                     
│Joker recieves back in PM: Successfully │             │                                                     
│      blacklisted jabbathehutt1234      │             │                                                     
│Can't blacklist captcoe, they are a mod │ ◀───────────┘                                                     
│   Gallowboob is already blacklisted    │                                                                   
│                                        │                                                                   
│                                        │                                                                   
│                                        │                                                                   
│                                        │                                                                   
│                                        │                                                                   
│                                        │                                                                   
└────────────────────────────────────────┘                                                                   
```

**Comment by TheLonelyGhost** [comment]
Several comments here:

---

Regarding multiple directives per message, I think this is a bit of overkill. It would significantly balloon the complexity, subsequently negatively affecting the maintenance costs, and the net benefit would be pretty minimal. It's super easy to send 2 separate messages for the once-in-a-while admin directives to the bot, plus you get that request-response lifecycle thing like you outlined with the above flowchart.

I want to be clear, this is intended to be an admin override of default bot behavior. If there's something here that happens regularly, we should be building it into the automation of the bots here, not relying on human interaction if we can help it.

---

As for structure, I can't think of a reason why we would want anything more than the message body to be passed to a handler method like above (excluding the `config` object), but I suppose it is possible. We'll address that if it becomes an issue.

The message body I think that should be left up to each handler. It seems too early to prescribe a standard layout for all the directives. My experiences with these situations have been that it'll hurt more to remove an existing schema to replace it than if we leave it relatively free-form per directive and apply a schema (if necessary) later.

---

I do want to stress that any of these RPC calls should be logged heavily, at least _that_ they're occurring and who invoked them. It's a huge security concern if we're exposing control of bot functions to others if we can't produce an audit trail. It might also help us track down if a mod's credentials have been compromised. 🤷‍♂️

**Comment by perryprog** [comment]
Awesome, I suppose the caller on these functions could auto-log it, and if needed, we can also log within each handler.

> Regarding multiple directives per message, I think this is a bit of overkill. 

This is something that's handed per function, it's really just the "syntax" of each admin command. As you can see in my example function, it takes virtually no effort to add more support for that, and not all functions would do that. (i.e. `ping`)

I'm thinking of moving off of everything being an admin command, and having some normal commands (i.e. `ping`, again) that let you look at stats or other things — again, it'll be incredibly easy to add support for this.

**Comment by TheLonelyGhost** [comment]
I see what you mean about implementation difficulty being trivial, but we have to keep in mind our target audience. Here's the use case I'm thinking of:

I'm a mod and, when browsing from my phone, I see that someone is being a jerk and claiming a bunch of posts, but letting them sit without working on them. My incentive is to stop the bleeding (so to speak) as soon as possible, then cleanup the damage as best I can. That would start with banning the user from accepting new posts (blacklisting).

Right now, I would have to post to our mod slack channel in hopes that someone else is at their desktop in order to handle the situation. The ideal situation is to message the bot from my phone, telling it to stop listening to that user and we can deal with the fallout once I'm at a computer again.

This use case means we want to keep the interface as simple as possible, avoiding any unnecessary verbosity. A CSV might be too much for someone to have to type out on their mobile device. Do you have another format that might be as simple for a non-technical user as newline separated list?

**Comment by perryprog** [comment]
Sorry, I mean there would be a CSV file _defining_ all of the admin commands, and that file would automatically call the appropriate function, mark the message as read, etc. etc.

The actual format for the PM message (which you can see in the flowchart above) would be newline separated, so you could just pm
```
Subject: !blacklist
Body: ReallyAnnoyingJerk
```


I hope that clears things up!

**Comment by perryprog** [comment]
Just to be clear, I think I can handle this issue. Working on a first draft now, it's so far much easier than I thought it would be.

**Comment by TheLonelyGhost** [comment]
Ah, the CSV manifest that describes the available commands and how to invoke them. I see.

@itsthejoker and I were discussing using JSON to that end, and we could essentially build a SOAP service using Reddit PMs as the transport mechanism, but that's overkill in the worst way, IMHO.

For documenting how to interact with each admin command, I'd say we can stick with python docstrings. We can map the subject string to a method using a dict's `get()` method to get a reference to the handler method:

```python

def handle_blacklist(msg, config):
    pass


def handle_unknown_command(msg, config):
    pass


MAP = {
    'blacklist': handle_blacklist,
}


def main(msg, config):
    if str(msg.subject).startswith('!'):
        func = MAP.get(msg.subject[1:].lower(), handle_unknown_command)
    else:
        raise NotImplementedError

    func(msg, config)
```

**Comment by perryprog** [comment]
Yeah, @itsthejoker told me about that. I also won't be able to work on probably anything for a bit, due to school work and that sorta thing, but I'll squeeze work in when I have time.
