### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#75]
@laurajohman has offered to help us with writing or beefing up documentation for the repos if there's anything we don't have a good handle on. Please use this issue to track topics / items which can be explained better.

**Comment by perryprog** [comment]
Expand on development cycle and stuff. Personally I use anaconda, but I believe everyone is using virtualenv?

**Comment by TheLonelyGhost** [comment]
Yep, I have a virtualenv setup here. I use pyenv for managing multiple python versions and direnv for automatically activating a virtualenv and python version upon entering a project directory.

Have been meaning to blog about it, so this may be the kick in the rear to do so.

Eventually I’d like to use tox so we can test locally against multiple versions of python and invoke the same tests.

@perryprog some basic suggested development flow is actually buried in our CONTRIBUTING.md doc if you’re interested.

**Comment by TheLonelyGhost** [comment]
Docs on what is available from the library’s API standpoint would be nice. We should see where we are framework wise in running Pydoc.

**Comment by laurajohman** [comment]
yo - Joker sent me: may have to explain some things to me as I'm used to Agile methods but I can see if I can do it. :)
