### ISSUE TITLE
Add smaller CSS button for list items

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#8]
We have a CSS buttons using headers for the subreddit, but we need a smaller (yet still good-looking) button that we can use in list formats for the sidebar.

**Comment by TheLonelyGhost** [comment]
Is this still relevant @itsthejoker and @Kumalumajuma ? Stale?

**Comment by itsthejoker** [comment]
With the incoming Reddit redesign, this is no longer valid. Closing.
