### ISSUE TITLE
Ping a user and Slack when a post is in progress for a long time.

### ISSUE THREAD

**Issue by perryprog** [GrafeasGroup/tor#80]
Basically the title.

If a user accepts the CoC, and leaves it because they don't like it or something, or they give up on a transcription and don't care enough to ask a mod to unclaim, the post will remain in progress and the FakeTor script will have to be lucky enough to catch it.

I propose if a post is flaired inprogress for +12 hours, to ping Slack and send a message reminding the person about their transcription. If there's no reply/they say they aren't interested, set it back to unclaimed.

**Comment by arfie** [comment]
Not sure we need this. We rarely have abandoned claims, and have only had
one person ever not accept the CoC. When a post stays "in progress" for a
while we usually find out eventually, and if the call is older than 12
hours it usually wouldn't really be worth transcribing anymore anyway. For
the CoC, we get a notification every time someone accepts it, and we
personally review each one. Once the change for claiming before accepting
the CoC is through, we should move that notification to the moment of
claiming and it will have the same effect.

Not saying this is a bad idea – it would certainly be helpful in some
cases. But I don't think it's worth putting time and API calls (our most
valuable resource, and the sole reason we have multiple bots) into.

Op vr 8 dec. 2017 21:27 schreef Perry Fraser <notifications@github.com>:

**Comment by perryprog** [comment]
Oops, forgot to add this.

<img width="745" alt="screen shot 2017-12-08 at 5 05 29 pm" src="https://user-images.githubusercontent.com/12972285/33787163-05761056-dc3a-11e7-944e-ec549efe38de.png">

Basically, I don't think it should really matter, but I figured I'd make an issue from my conversation with @TheLonelyGhost.

**Comment by TheLonelyGhost** [comment]
To clarify, this was one of many questions, followed by:

> thelonelyghost: Are the transcription claims so short lived that it matters?

Sounds like it's not an issue now, so adding extra code for what _might_ happen like this wouldn't be a good idea. We'll revisit this if it becomes an issue.
