### ISSUE TITLE
flair colours/levels adjustment

### ISSUE THREAD

**Issue by astheriae** [GrafeasGroup/tor#96]
Adjust flair levels to -

Initiates: 0-49

Green: 50-99

Teal: 100-249

Purple: 250-499

Golden: 500-999

Diamond: 1000+

**Comment by TheLonelyGhost** [comment]
Slight adjustment from conversation elsewhere: Shouldn't the initiate level start at `1` instead of `0` and go to `49`?

**Comment by itsthejoker** [comment]
Yes, initiate should start at 1. I'll try to look at this here in a bit.
