### ISSUE TITLE
checking if user has accepted the CoC

### ISSUE THREAD

**Issue by astheriae** [GrafeasGroup/tor#97]
an admin command for checking if username has accepted the CoC

for finding transcriptions completed 'In the wild' and creating a notification in slack

**Comment by perryprog** [comment]
May be nice to connect this to the new up coming queue system, plus a Discord/Slack bot.

Otherwise a Reddit "command" should be fine.

**Comment by itsthejoker** [comment]
From #dev:

We have a set of every single post ID that we’ve ever looked at
[12:59 PM]
we can set up a super simple script to monitor all incoming comments from Reddit using the `stream()` function
[12:59 PM]
if a comment has the footer in it, check the parent post ID against the redis set
[12:59 PM]
if the parent post ID is not in our set, ping slack.

**Comment by TheLonelyGhost** [comment]
I could see an argument for the admin commands as a whole being a slack bot, but we also are unsure if we'll be able to stick with slack long-term for accessibility reasons.

I don't think it would receive any great benefit by waiting until the worker-queue thing is released versus the existing way we address admin commands. 🤷‍♂️

**Comment by perryprog** [comment]
I'm familiar enough with Chat ops in both Slack and Discord that it should be a problem, plus the learning experience, and all that stuff.

I think it's still a good idea to wait until the worker queue system for this.

Maybe add a "waiting for rewrite" tag or something?

**Comment by TheLonelyGhost** [comment]
We currently have this as a command that can be run via a command directly on the server, which will work in the meantime, but not yet transformed into something accessible by non-sysadmin types.

Since we have a workaround, I'm going to make an execu-decision and say this should be implemented on the modchat bot instead. :)
